config/routes.rb
Terribletracker::Application.routes.draw do
  devise_for :users

  resources :projects do
    resources :user_stories
  end

  root to: "projects#index"

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end

  resources :story_owners

  resources :clients

end

app/models/user_story.rb
# == Schema Information
#
# Table name: user_stories
#
#  id           :integer          not null, primary key
#  title        :string(255)      not null
#  content      :text
#  estimate     :integer
#  project_id   :integer          not null
#  complexity   :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  story_status :string(255)      default("Unstarted")
#

class UserStory < ActiveRecord::Base
  attr_accessible  :story_status, :complexity, :content, :estimate, :project_id, :title

  validates :title, :project, :content, :estimate, :complexity, :story_status, {
    presence: true
  }

  validates :project_id, {
    numericality: true
  }

  belongs_to :project

  has_many :story_owners

  has_many :users, {
    through: :story_owners
  }
end

app/controllers/user_stories_controller.rb
class UserStoriesController < ApplicationController
  def new
    @project = Project.find(params[:project_id])
    @user_story = UserStory.new
  end

  def create
    @project = Project.find(params[:project_id])
    @user_story = @project.user_stories.new
    @user_story.update_attributes(params[:user_story])

    if @user_story.save
      flash[:notice] = "User Story created"
      redirect_to @project
    else
      flash[:error] = "There was an error creating your user story"
      redirect_to new_project_user_story_path
    end
  end

  def show
    @project = Project.find(params[:project_id])
    @user_story = UserStory.find(params[:id])
  end

  def edit
    @project = Project.find(params[:project_id])
    @user_story = UserStory.find(params[:id])
  end

  def update
    @project = Project.find(params[:project_id])
    @user_story = UserStory.find(params[:id])
    if params[:user_story][:title].nil?
      @user_story.update_attributes(params[:user_story])
      redirect_to @project
    else
      if @user_story.update_attributes(params[:user_story])
        flash[:notice] = "User story updated"
        redirect_to project_user_story_path(@project, @user_story)
      else
        flash[:error] = "There was an error updating your user story"
        redirect_to project_user_story_path(@project, @user_story)
      end
    end
  end

  def destroy
    @project = Project.find(params[:project_id])
    @user_story = UserStory.find(params[:id])

    if @user_story.delete
      flash[:notice] = "User story deleted"
      redirect_to @project
    else
      flash[:error] = "There was an error deleting your user story"
      redirect_to @project
    end
  end
end

app/views/user_stories/_edit_user_story_form.html.erb
<%= simple_form_for [@project, @user_story] do |f| %>

  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.input :complexity %>
  <%= f.input :estimate %>

  <%= f.submit %>
<% end %>

app/views/user_stories/_user_story_form.html.erb
<%= simple_form_for [@project, @user_story] do |f| %>

  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.input :complexity %>
  <%= f.input :estimate %>

  <%= f.submit %>
<% end %>

app/views/user_stories/edit.html.erb
<div class="row">
  <div class="span12">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-error" %>
        <%= flash[:error] %>
      </div>
    <% end %>
    <h1>Edit User Story</h1>
    <%= render 'edit_user_story_form' %>

    <%= link_to "Back", projects_path %>
  </div>
</div>

app/views/user_stories/new.html.erb
<div class="row">
  <div class="span12">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-error" %>
        <%= flash[:error] %>
      </div>
    <% end %>
    <h1>New User Story</h1>
    <%= render 'user_story_form' %>

    <%= link_to "Back", projects_path %>
  </div>
</div>

app/views/user_stories/show.html.erb
<div class="row">
  <div class="span12">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-error" %>
        <%= flash[:error] %>
      </div>
    <% end %>
    <div class="userstorycontext">
      <%= link_to "Edit", edit_project_user_story_path(@project, @user_story) %>
      <%= link_to "Delete", project_user_story_path(@project, @user_story), method: :delete %>
    </div>
    <h1><%= @project.title %></h1>
    <p><strong>Client:</strong> TODO: ADD CLIENT</p>
    <p><strong>Budget:</strong> <%= @project.budget %></p>
    <p><strong>Weekly Rate:</strong> <%= @project.weekly_rate %></p>
      <table class="table table-striped">
        <thead>
          <th>Title</th>
          <th>Story</th>
          <th>Complexity</th>
          <th>Estimate</th>
          <th>Developer</th>
        </thead>
        <tbody>
          <tr>
            <td><%= @user_story.title %></td>
            <td><%= @user_story.content %></td>
            <td><%= @user_story.complexity %></td>
            <td><%= @user_story.estimate %></td>
            <td>TODO: ADD DEVELOPER</td>
          </tr>
        </tbody>
      </table>
      <br>
    <br>
    <%= link_to "Back", project_path(@project) %>
  </div>
</div>