config/routes.rb
Terribletracker::Application.routes.draw do
  devise_for :users

  resources :projects do
    resources :user_stories
  end

  root to: "projects#index"

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end

  resources :story_owners

  resources :clients

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id          :integer          not null, primary key
#  title       :string(255)      not null
#  budget      :integer
#  weekly_rate :integer
#  due_date    :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Project < ActiveRecord::Base
  attr_accessible :budget, :due_date, :title, :weekly_rate

  validates :title, :budget, :weekly_rate, {
    presence: true,
  }

  has_many :user_stories, {
    dependent: :destroy,
    inverse_of: :project
  }

  has_many :memberships

  accepts_nested_attributes_for :user_stories

  has_many :users, {
    through: :memberships
  }

  def client
    self.memberships.each { |membership| return membership.user if membership.role == "client" }
    return nil
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @user = current_user
    @projects = @user.projects
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])

    if @project.save
      @membership = current_user.memberships.build(project: @project, role: "owner")
      @membership.save
      redirect_to @project, notice: "Project successfully created"
    else
      redirect_to new_project_path, notice: "There was an error creating your project"
    end
  end

  def show
    begin
      @user = current_user
      @project = @user.projects.find(params[:id])

      @user_stories = @project.user_stories.order("created_at DESC").all
      @story_owner = StoryOwner.new
    rescue
      flash[:error] = "You don't have permission to access that project"
      redirect_to projects_path
    end


  end

  def destroy
    @project = Project.find(params[:id])

    if @project.delete
      flash[:notice] = "Project deleted"
      redirect_to projects_path
    else
      flash[:error] = "There was an error deleting your project"
      redirect_to projects_path
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    params[:project].delete(:client)

    if @project.update_attributes(params[:project])
      flash[:notice] = "Project updated"
      redirect_to @project
    else
      flash[:error] = "Oops. There was an error updating your project."
      redirect_to @project
    end
  end
end

app/views/projects/_change_story_status.html.erb
<% if user_story.story_status == "Unstarted" %>
  <td>
    <%= form_for [@project, user_story], { :class => "story_status" } do |f| %>

      <%= f.hidden_field "story_status", { value: "Started" } %>
      <%= f.submit "#{user_story.story_status}", { :class => "badge"} %>
    <% end %>
  </td>
<% elsif user_story.story_status == "Started" %>
  <td><span class="badge badge-info">
    <%= user_story.story_status %>
  </td></span>
<% elsif user_story.story_status == "Code Review" %>
  <td><span class="badge badge-warning">
    <%= user_story.story_status %>
  </td></span>
<% elsif user_story.story_status == "Completed" %>
  <td><span class="badge badge-success">
    <%= user_story.story_status %>
  </td></span>
<% end %>

app/views/projects/_edit_project_form.erb
<%= simple_form_for @project do |f| %>

  <%= f.input :title %>
  <%= f.input :budget %>
  <%= f.input :weekly_rate %>

  <%= f.submit %>
<% end %>

app/views/projects/_edit_project_form.html.erb
<%= simple_form_for @project do |f| %>

  <%= f.input :title %>
  <%= f.input :budget %>
  <%= f.input :weekly_rate %>

  <%= f.submit %>
<% end %>

app/views/projects/_project_form.html.erb
<%= simple_form_for @project do |f| %>

  <%= f.input :title %>
  <%= f.input :budget %>
  <%= f.input :weekly_rate %>

  <%= f.submit %>
<% end %>

app/views/projects/_story_status.html.erb
<% @user_stories.each do |user_story| %>
  <tr>
    <% if user_story.story_status == "Unstarted" %>

      <td>
        <%= form_for [@project, user_story], { :class => "story_status" } do |f| %>

          <%= f.hidden_field "story_status", { value: "Started" } %>
          <%= f.submit "#{user_story.story_status}", { :class => "badge"} %>
        <% end %>
      </td>

    <% elsif user_story.story_status == "Started" %>

      <td>
        <%= form_for [@project, user_story], { :class => "story_status" } do |f| %>

          <%= f.hidden_field "story_status", { value: "Code Review" } %>
          <%= f.submit "#{user_story.story_status}", { :class => "badge badge-info"} %>
        <% end %>
      </td>

    <% elsif user_story.story_status == "Code Review" %>

       <td>
        <%= form_for [@project, user_story], { :class => "story_status" } do |f| %>

          <%= f.hidden_field "story_status", { value: "Completed" } %>
          <%= f.submit "#{user_story.story_status}", { :class => "badge badge-warning"} %>
        <% end %>
      </td>

    <% elsif user_story.story_status == "Completed" %>

      <td><span class="badge badge-success complete">
        <%= user_story.story_status %>
      </td></span>

    <% end %>

    <td><%= link_to "#{user_story.title}", project_user_story_path(@project, user_story) %></td>
    <td><%= user_story.content %></td>
    <td><%= user_story.complexity %></td>
    <td><%= user_story.estimate %></td>
    <% if user_story.users.length > 0 %>
      <td><span class="badge badge-info"><%= user_story.users.first.email %></span></td>
    <% else %>
      <td>
        <%= form_for @story_owner, { :class => "story_status" } do |f| %>
          <%= f.hidden_field :project, { value: @project.id } %>
          <%= f.hidden_field :user_id, { value: current_user.id } %>
          <%= f.hidden_field :user_story_id, { value: user_story.id } %>
          <%= f.submit "No one assigned", { :class => "badge" } %>
        <% end %>
      </td>
    <% end %>
  </tr>
<% end %>

app/views/projects/edit.html.erb
<div class="row">
  <div class="span12">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-error" %>
        <%= flash[:error] %>
      </div>
    <% end %>
    <h1>Edit Project</h1>
    <%= render 'edit_project_form' %>

    <%= link_to "Back", projects_path %>
  </div>
</div>

app/views/projects/index.html.erb
<div class="row">
  <div class="span12">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-error" %>
        <%= flash[:error] %>
      </div>
    <% end %>
    <h1>Projects</h1>
    <table class="table table-striped">
      <thead>
        <th>Title</th>
        <th>Client</th>
        <th>Budget</th>
        <th>Weekly Rate</th>
      </thead>
      <tbody>
        <% @projects.each do |project| %>
          <tr>
            <td><%= link_to "#{project.title}", project_path(project) %></td>
            <% if project.client %>
              <td><%= link_to "#{project.client.email}", edit_client_path(project) %></td>
            <% else %>
              <td><%= link_to "Add client", new_client_path(project) %></td>
            <% end %>
            <td><%= project.budget %></td>
            <td><%= project.weekly_rate %></td>
            <td><%= link_to "Edit", edit_project_path(project) %></td>
            <td><%= link_to "Delete", project_path(project), method: :delete %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to "New Project", new_project_path %>
  </div>
</div>

app/views/projects/new.html.erb
<div class="row">
  <div class="span12">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-error" %>
        <%= flash[:error] %>
      </div>
    <% end %>
    <h1>New Project</h1>
    <%= render 'project_form' %>

    <%= link_to "Back", projects_path %>
  </div>
</div>

app/views/projects/show.html.erb
<div class="row">
  <div class="span12">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-error" %>
        <%= flash[:error] %>
      </div>
    <% end %>
    <h1><%= @project.title %></h1>
    <% if @project.client == nil %>
      <p><strong>Client:</strong> <%= link_to "Add Client", new_client_path(@project) %></p>
    <% else %>
      <p><strong>Client:</strong> <%= link_to "#{@project.client.email}", edit_client_path(@project) %></p>
    <% end %>
    <p><strong>Budget:</strong> <%= @project.budget %></p>
    <p><strong>Weekly Rate:</strong> <%= @project.weekly_rate %></p>
    <% if @project.user_stories.length > 0 %>
      <table class="table table-striped">
          <thead>
            <th>Status</th>
            <th>Title</th>
            <th>Story</th>
            <th>Complexity</th>
            <th>Estimate</th>
            <th>Developer</th>
          </thead>
          <tbody>
            <%= render 'story_status' %>
          </tbody>
        </table>
      <% end %>
      <br>
    <%= link_to "Add User Stories", new_project_user_story_path(@project) %>
    <br>
    <%= link_to "Back", projects_path %>
  </div>
</div>